# Generated by Django 2.2.3 on 2019-09-29 22:38

from django.db import migrations

def populate_status_code(apps, schema_editor):
    StatusCode = apps.get_model('services', 'StatusCode')
    with open('services/populate_data/status_codes.csv', 'r', encoding='UTF8') as data:
        for line in data.readlines():
            line = line.split(';')
            status_code = StatusCode(code=int(line[0]), description=line[1])
            status_code.save()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status_code),
    ]
