# Generated by Django 2.2.3 on 2019-09-29 23:12

from django.db import migrations

def methods(apps, schema_editor):
    Method = apps.get_model('services', 'Method')
    with open('services/populate_data/methods.csv', 'r', encoding='UTF8') as data:
        for line in data.readlines():
            line = line.split(';')
            method = Method(verb=line[0], description=line[1])
            method.save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190929_1808'),
    ]

    operations = [
        migrations.RunPython(methods),
    ]
