# Generated by Django 2.2.3 on 2019-10-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190929_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='statuscode',
            options={'ordering': ['code']},
        ),
    ]
