# Generated by Django 2.2.3 on 2019-10-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190930_2300'),
        ('dependencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='destination_service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_service', to='services.Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependency',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.Service'),
        ),
    ]
